### ISSUE TITLE
invert_logic seemed to be ignored

### ISSUE THREAD

**Issue by gcs278** [jpcornil-git/HA-mcp23017#3]
Thanks for putting this together - I've been banging my head against the wall trying to fix [this](https://github.com/home-assistant/core/issues/31867#issuecomment-872927051).

I installed the component and everything seemed to work correctly, but the invert_logic flag seemed to be ignored from my configuration.yaml:
```
- platform: mcp23017
  i2c_address: 0x21
  pins:
    12: Front Bench Switch
  scan_interval: 1
  invert_logic: true
```

I had to go to the integration page and manually find "Front Bench Switch" and configure -> invert_logic checkbox. That worked, but I have quite a lot of sensors I have to go do this to.

Am I doing something wrong or is this a bug?

Thanks!
